### ISSUE TITLE
failing to load API on gateway

### ISSUE THREAD

**Issue by harlantwood** [core-network/client-threejs#7]
eg https://ipfs.io/ipfs/QmcGV7hbNmQneiwcFwQ3Nk5GmNiWpvbtJN7FqtQcEyLsbo/#QmWATgZe8Q2hu89JadmT7zqTQkj8C16Cz9nHNnSJLdsywZ

fails with

`GET https://ipfs.io:80/:undefined/api/v0/commands?stream-channels=true`

Note the `:undefined` -- probably a port number attempt?  Fails on servers running on port 80.

Try upgrading nodesphere to latest ipfs api node module first.

full stacktrace:
```
GET https://ipfs.io:80/:undefined/api/v0/commands?stream-channels=true 
net::ERR_SSL_PROTOCOL_ERRORClientRequest._onFinish @ bundle.js:82809(anonymous function) @ bundle.js:82751EventEmitter.emit @ bundle.js:25372finishMaybe @ bundle.js:75088endWritable @ bundle.js:75098Writable.end @ bundle.js:75063ClientRequest.end @ bundle.js:82939Request.end @ bundle.js:78690end @ bundle.js:77852(anonymous function) @ bundle.js:77866Item.run @ bundle.js:72273drainQueue @ bundle.js:72243
bundle.js:5374 Unhandled rejection RequestError: TypeError: Failed to fetch
    at new RequestError (https://ipfs.io/ipfs/QmcGV7hbNmQneiwcFwQ3Nk5GmNiWpvbtJN7FqtQcEyLsbo/bundle.js:75151:15)
    at Request.RP$callback [as _callback] (https://ipfs.io/ipfs/QmcGV7hbNmQneiwcFwQ3Nk5GmNiWpvbtJN7FqtQcEyLsbo/bundle.js:75239:32)
    at self.callback (https://ipfs.io/ipfs/QmcGV7hbNmQneiwcFwQ3Nk5GmNiWpvbtJN7FqtQcEyLsbo/bundle.js:77486:22)
    at Request.EventEmitter.emit (https://ipfs.io/ipfs/QmcGV7hbNmQneiwcFwQ3Nk5GmNiWpvbtJN7FqtQcEyLsbo/bundle.js:25375:17)
    at Request.onRequestError (https://ipfs.io/ipfs/QmcGV7hbNmQneiwcFwQ3Nk5GmNiWpvbtJN7FqtQcEyLsbo/bundle.js:78155:8)
    at EventEmitter.emit (https://ipfs.io/ipfs/QmcGV7hbNmQneiwcFwQ3Nk5GmNiWpvbtJN7FqtQcEyLsbo/bundle.js:25375:17)
    at https://ipfs.io/ipfs/QmcGV7hbNmQneiwcFwQ3Nk5GmNiWpvbtJN7FqtQcEyLsbo/bundle.js:82819:9
```

**Comment by harlantwood** [comment]
Tried updating nodespheres version of IPFS API, no change.

**Comment by harlantwood** [comment]
Fixed
